link_manager/accounts/urls.py
from django.conf.urls.defaults import *
from accounts.forms import UserCreationFormCustomized, UserChangeFormCustomized, OpenIDForm
from django.utils.functional import lazy
from django.core.urlresolvers import reverse
from django.contrib.auth.views import login, logout, password_change,\
    password_change_done, password_reset, password_reset_complete,\
    password_reset_done, password_reset_confirm
from django.views.generic import create_update, simple
from accounts.views import openid_start, openid_complete, user_change

reverse_lazy = lazy(reverse, str)

urlpatterns = patterns('',
                       url(r'^login/$', login, {'template_name': 'login.html', },'login'),
                       url(r'^logout/$', logout, {'template_name': 'logout.html'},'logout'),
                       url(r'^password_change/$', password_change, {'template_name': 'password_change.html'},'password_change'),
                       url(r'^password_change_done/$', password_change_done, {'template_name': 'password_change_done.html'},'password_change_done'),
                       url(r'^password_reset/$', password_reset, {'template_name': 'accounts/password_reset.html', 'email_template_name':'password_reset_email.html'},'password_reset'),
                       url(r'^password_reset_confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)$', password_reset_confirm, {'template_name': 'password_reset_confirm.html'},'password_reset_confirm'),
                       url(r'^password_reset_complete/$', password_reset_complete, {'template_name': 'password_reset_complete.html'},'password_reset_complete'),
                       url(r'^password_reset_done/$', password_reset_done, {'template_name': 'password_reset_done.html'},'password_reset_done'),
) 

urlpatterns += patterns('',
                        url(r'^signup/$', create_update.create_object, {'form_class':UserCreationFormCustomized, 'template_name': 'signup.html', 'post_save_redirect':reverse_lazy('signup_complete')}, "signup"),
                        url(r'^signup_complete/$', simple.direct_to_template, {'template': 'signup_complete.html',},'signup_complete'),
                        url(r'^user_change_complete/$', simple.direct_to_template, {'template': 'user_change_complete.html',},'user_change_complete'),
                        #url(r'^openid_complete/$', 'simple.direct_to_template', {'template': 'openid_login_complete.html',},'openid_login_complete'),

                     )

urlpatterns += patterns('',
                        url(r'^openid/$', openid_start, {'authentication_form':OpenIDForm, 'template_name': 'openid_login.html','default_redirect':'/'},'openid_login'),
                        url(r'^openid_complete/$', openid_complete,{}, 'openid_complete'),
                        url(r'^user_change/$', user_change, {'form_class':UserChangeFormCustomized, 'template_name': 'user_change.html','post_save_redirect':reverse_lazy('user_change_complete')},'user_change'),
                     )

link_manager/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'links.views.home', name='home'),
    
    url(r'^', include('link_manager.links.urls')),
    url(r'^accounts/', include('link_manager.accounts.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

link_manager/accounts/models.py
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User

class Nonce(models.Model):
    server_url = models.URLField()
    timestamp = models.IntegerField()
    salt = models.CharField(max_length=50 )

    def __unicode__(self):
        return "Nonce: %s" % self.nonce

class Association(models.Model):
    server_url = models.TextField(max_length=2047)
    handle = models.CharField(max_length=255)
    secret = models.TextField(max_length=255) # Stored base64 encoded
    issued = models.IntegerField()
    lifetime = models.IntegerField()
    assoc_type = models.TextField(max_length=64)

    def __unicode__(self):
        return "Association: %s, %s" % (self.server_url, self.handle)

class OpenIDUser(models.Model):
    user = models.ForeignKey(User)
    claimed_id = models.TextField(max_length=2047, unique=True)
    display_id = models.TextField(max_length=2047)

admin.site.register(OpenIDUser)
admin.site.register(Nonce)
admin.site.register(Association)

link_manager/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User

class OpenIDForm(forms.Form):
    openid_url = forms.URLField(max_length=80, label='Open ID Url')

    def __init__(self, request=None, *args, **kwargs):
        """
        If request is passed in, the form will validate that cookies are
        enabled. Note that the request (a HttpRequest object) must have set a
        cookie with the key TEST_COOKIE_NAME and value TEST_COOKIE_VALUE before
        running this validation.
        """
        self.request = request
        self.user_cache = None
        super(OpenIDForm, self).__init__(*args, **kwargs)
        
    def clean(self):
        if self.request:
            if not self.request.session.test_cookie_worked():
                raise forms.ValidationError(_("Your Web browser doesn't appear to have cookies enabled. Cookies are required for logging in."))
        return self.cleaned_data
    class Media:
        css = {
            'all': ('css/openid.css',),
        }
        js = ('js/openid-jquery.js', )


class UserCreationFormCustomized(UserCreationForm):
    UserCreationForm.Meta.fields = ("username", "email", "first_name", "last_name", )
    
    def __init__(self, *args, **kwargs):
        super(UserCreationFormCustomized, self).__init__(*args, **kwargs)
        self.fields['email'].required=True

class UserCreationFormWithEmail(UserCreationForm):
    UserCreationForm.Meta.fields = ("username", "first_name", "last_name", )
    
    def __init__(self, *args, **kwargs):
        super(UserCreationFormWithEmail, self).__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['username']=forms.EmailField(label=_('Email'),help_text=_('This will be your username'))  

    def save(self, commit=True):
        user = super(UserCreationFormWithEmail, self).save(commit=False)
        user.email = self.cleaned_data["username"]
        if commit:
            user.save()
        return user

class UserChangeFormCustomized(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email','first_name','last_name')
    
class UserChangeFormWithEmail(UserChangeForm):
    UserChangeForm.Meta.fields = ("username", "first_name", "last_name", )
    
    def __init__(self, *args, **kwargs):
        super(UserChangeFormWithEmail, self).__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['username']=forms.EmailField(label=_('Email'),help_text=_('This will be your username'))
        self.fields['username'].widget.attrs['readonly'] = True

        
    def save(self, commit=True):
        user = super(UserChangeFormWithEmail, self).save(commit=False)
        user.email = self.cleaned_data["username"]
        if commit:
            user.save()
        return user

link_manager/accounts/views.py
from django.http import HttpResponseRedirect, HttpResponse
from accounts.utils import DjangoOpenIDStore #@UnresolvedImport
from django.core.urlresolvers import reverse
from django.template.context import RequestContext
from django.shortcuts import render_to_response
from django.views.generic.create_update import update_object
from accounts.forms import UserChangeFormWithEmail, OpenIDForm
from django.contrib.auth import REDIRECT_FIELD_NAME, authenticate, login
from django.contrib.sites.models import Site, RequestSite
from openid.yadis.discover import DiscoveryFailure
from django.template.loader import render_to_string

from openid.consumer.consumer import Consumer, SUCCESS, FAILURE, CANCEL
from openid.extensions import ax, sreg
import urllib


def render_failure(request, message, status=403,
                           template_name='openid_failure.html'):
    data = render_to_string(template_name, dict(message=message),context_instance=RequestContext(request))
    return HttpResponse(data, status=status)

def make_consumer(request):
    session = request.session.setdefault('OPENID', {})
    store = DjangoOpenIDStore()
    return Consumer(session, store)

def openid_start(request, template_name='openid_login.html', redirect_field_name=REDIRECT_FIELD_NAME, default_redirect='/',
          authentication_form=OpenIDForm):
    
    redirect_to = request.REQUEST.get(redirect_field_name) or default_redirect
    
    if request.method == 'POST':
        form = authentication_form(request, data=request.POST)
        if form.is_valid():
            openid_url = form.cleaned_data['openid_url']
            consumer = make_consumer(request)
            try:
                openid_request = consumer.begin(openid_url)
            except DiscoveryFailure, exc:
                return render_failure(request, "OpenID discovery error: %s" % (str(exc),), status=500)
            if openid_request.endpoint.supportsType(ax.AXMessage.ns_uri):
                fetch_request = ax.FetchRequest()
                # We mark all the attributes as required, since Google ignores
                # optional attributes.  We request both the full name and
                # first/last components since some providers offer one but not
                # the other.
                for (attr, alias) in [
                    ('http://axschema.org/contact/email', 'email'),
                    ('http://axschema.org/namePerson', 'fullname'),
                    ('http://axschema.org/namePerson/first', 'firstname'),
                    ('http://axschema.org/namePerson/last', 'lastname'),
                    ('http://axschema.org/namePerson/friendly', 'nickname'),
                    # The myOpenID provider advertises AX support, but uses
                    # attribute names from an obsolete draft of the
                    # specification.  We request them for compatibility.
                    ('http://schema.openid.net/contact/email', 'old_email'),
                    ('http://schema.openid.net/namePerson', 'old_fullname'),
                    ('http://schema.openid.net/namePerson/friendly', 'old_nickname')]:
                    fetch_request.add(ax.AttrInfo(attr, alias=alias, required=True))
                openid_request.addExtension(fetch_request)
            else:
                openid_request.addExtension(
                    sreg.SRegRequest(optional=['email', 'fullname', 'nickname']))
            return_to = request.build_absolute_uri(reverse(openid_complete))
            return_to += "?"+urllib.urlencode({redirect_field_name: redirect_to})
            if request.session.test_cookie_worked():
                request.session.delete_test_cookie()
            return render_openid_request(request, openid_request, return_to)

    else:
        form = authentication_form(request)
    
    request.session.set_test_cookie()
    
    if Site._meta.installed: #@UndefinedVariable
        current_site = Site.objects.get_current()
    else:
        current_site = RequestSite(request)
    
    return render_to_response(template_name,
                              {'form':form,
                               redirect_field_name:redirect_to,
                               'site': current_site,
                               'site_name': current_site.name,
                               },
                              context_instance=RequestContext(request))

def render_openid_request(request, openid_request, return_to, trust_root=None):
    """Render an OpenID authentication request."""
    trust_root = request.build_absolute_uri('/')

    if openid_request.shouldSendRedirect():
        redirect_url = openid_request.redirectURL(trust_root, return_to)
        return HttpResponseRedirect(redirect_url)
    else:
        form_html = openid_request.htmlMarkup(trust_root, return_to, form_tag_attrs={'id': 'openid_message'})
        return HttpResponse(form_html, content_type='text/html;charset=UTF-8')

def openid_complete(request, redirect_field_name=REDIRECT_FIELD_NAME):

    redirect_to = request.REQUEST.get(redirect_field_name, '')
    current_url = request.build_absolute_uri()

    consumer = make_consumer(request)
    openid_response = consumer.complete(dict(request.REQUEST.items()), current_url)

    if not openid_response:
        return render_failure(request, 'This is an OpenID relying party endpoint.')

    if openid_response.status == SUCCESS:
        user = authenticate(openid_response=openid_response)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(redirect_to)
            else:
                return render_failure(request, 'Disabled account')
        else:
            return render_failure(request, 'Unknown user')
    elif openid_response.status == FAILURE:
        return render_failure(
            request, 'OpenID authentication failed: %s' %
            openid_response.message)
    elif openid_response.status == CANCEL:
        return render_failure(request, 'Authentication cancelled')
    else:
        assert False, (
            "Unknown OpenID response type: %r" % openid_response.status)

## Create your views here.
#def signup(request, success_url=None,
#             form_class=UserCreationForm,
#             template_name='signup.html',
#             extra_context=None):
#    if request.method == 'POST':
#        form = form_class(data=request.POST, files=request.FILES)
#        if form.is_valid():
#            form.save()
#            # success_url needs to be dynamically generated here; setting a
#            # a default value using reverse() will cause circular-import
#            # problems with the default URLConf for this application, which
#            # imports this file.
#            return HttpResponseRedirect(success_url or reverse(signup_complete))
#    else:
#        form = form_class()
#    
#    if extra_context is None:
#        extra_context = {}
#    context = RequestContext(request)
#    for key, value in extra_context.items():
#        context[key] = callable(value) and value() or value
#    return render_to_response(template_name,
#                              { 'form': form },
#                              context_instance=context)

def user_change(request, form_class=UserChangeFormWithEmail, template_name='user_change.html', post_save_redirect=None):
    return update_object(request,
                         form_class=form_class,
                         object_id=request.user.id,
                         template_name=template_name,
                         post_save_redirect=post_save_redirect,
                         login_required=True
                         )

#
#def signup_complete(request, template_name='accounts/signup_complete.html'):
#    context = RequestContext(request)
#    return render_to_response(template_name, context)

link_manager/accounts/templates/base_accounts_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block content %}

<form method="post" action="" class="well" id="{%block formid%}form{%endblock%}">{% csrf_token %}
<fieldset>
<legend>{% block title %}{% endblock %}</legend>
{{ form.non_field_errors }}

{% if form.errors %}
{% block iferror %}
{% endblock %}

{% endif %}

{% block preform %}
{% endblock %}
{% for field in form.visible_fields %}
{{field.label_tag}}{% if field.help_text %} ({{ field.help_text }}){% endif %}
{{field|add_class:"span3"}} 
{%if field.errors%}
<span class="error" >
    {% for error in field.errors %}
    {{error}}
    {% endfor %}
</span>
{%endif%}
<br/>
{% if not forloop.last %}
<br/>
{% endif %}
{% endfor %}
<div class="form-actions">
    <button type="submit" class="btn btn-primary">{% block buttontext %}Save{% endblock %}</button>
    <button type="reset" class="btn">Cancel</button>
</div>
{% for hidden in form.hidden_fields %}
{{ hidden }}
{% endfor %}
{% block postform%}
{% endblock %}
</form>
</fieldset>
{% endblock %}

link_manager/accounts/templates/login.html
{% extends "base_accounts_form.html" %}

{% block iferror %}
Your username and password didn't match. <a href="{% url password_reset %}">Forgot password?</a>
{% endblock %}
{% block buttontext %}Login{% endblock %}

{% block title %}Login{% endblock %}

{% block postform %}
<hr/>
You can also login via <a href="{% url openid_login %}?next={{ next }}">OpenID</a><br />
Of you don't have a login yet, <a href="{% url signup %}">Signup</a>.
{% endblock %}

link_manager/accounts/templates/logout.html
{% extends "base.html" %}

{% block content %}

Logged out.

{% endblock %}

link_manager/accounts/templates/openid_failure.html
{% extends "base.html" %}

{% block content %}
Failure:
{{ message }}

{% endblock %}

link_manager/accounts/templates/openid_login.html
{% extends "base_accounts_form.html" %} 
{%block buttontext%}Login{%endblock%}
{% block title %}Open ID Login{% endblock %}
{% block head %}
{{ block.super }}
<script type="text/javascript">
	$(document).ready(function() {
	    /*openid.init('openid_identifier');*/
	    $('#id_openid_username_container').hide();
	    $('#choices a').hover(function(){
		    //window.alert($(this).attr('rel'));
		    var openid_url = $(this).attr('rel');
		    if(openid_url.match("{username}")) {
		    	$('#id_openid_url').val(openid_url.replace('{username}', $('#id_openid_username').val()));
		    }else {
		    	$('#id_openid_url').val(openid_url);
		    }
	    });
	    $('#choices a').click(function(){
	    	$('#choices a.selected').removeClass('selected');
		    $(this).addClass('selected');
		    var openid_url = $(this).attr('rel');
		    if(openid_url.match("{username}")) {
		    	$('#id_openid_username_container').show();
		    	$('#id_openid_username_label').text($('#id_openid_username').attr('alt').replace('{title}',$(this).attr('title')));
		    } else {
			    $('#id_openid_url').val();
			    $('#form').submit();
		    }
	    });
	    $('#id_openid_username').keyup(function(event) {
	    	var template = $('#choices a.selected').attr('rel');
	    	$('#id_openid_url').val(template.replace('{username}', $(this).val()));
    	});
	});
	</script>
{% endblock %}

{%block preform%}

<div id="choices" >
	<h3>Choose your login provider</h3>
	<a title="Google" id="google" rel="https://www.google.com/accounts/o8/id">Google</a>
	<a title="Yahoo" id="yahoo" rel="http://me.yahoo.com">Yahoo</a>
	<a title="AOL" id="aol" rel="http://openid.aol.com/{username}">AOL</a>
	<a title="myOpenID" id="myopenid" rel="http://myopenid.com/{username}">myOpenId</a>
	
</div>
<div id="id_openid_username_container" class="clear">
<label id="id_openid_username_label" for="id_openid_username">Username</label>
<input type="text" name="openid_username" id="id_openid_username"  class="span3" alt="{title} Username"/> 
<br/>
<button type="submit" class="btn">Login</button>
</div>
<hr />
<h3>or manually enter a Open ID Url:</h3>
{%endblock%}
{%block postform%}
<hr />
back to the
<a href="{% url login %}">regular Login</a>
{%endblock%} 
{% block endbody %}
{{ block.super }}

{% endblock %}

link_manager/accounts/templates/openid_login_complete.html
{% extends "base.html" %}

{% block content %}

Openid complete.

{% endblock %}

link_manager/accounts/templates/password_change.html
{% extends "accounts/base_accounts_form.html" %}

{% block title%}
Change your password
{% endblock %}

link_manager/accounts/templates/password_reset.html
{% extends "accounts/base_accounts_form.html" %}

{% block preform %}
Please enter your email address and we'll send you a link to recover your password.
{% endblock %}

{% block title %}Forgot my password?{% endblock %}

{% block buttontext %}Send reset link{% endblock %}

link_manager/accounts/templates/password_reset_complete.html
{% extends "base.html" %}

{% block content %}

Password reset complete.

{% endblock %}

link_manager/accounts/templates/password_reset_confirm.html
{% extends "accounts/base_accounts_form.html" %}

{%block preform%}
Please enter your new password
{%endblock%}

{%block buttontext%}Reset{%endblock%}

{%block title%}Reset Password{%endblock%}

link_manager/accounts/templates/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% trans "You're receiving this e-mail because you requested a password reset" %}
{% blocktrans %}for your user account at {{ site_name }}{% endblocktrans %}.

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url django.contrib.auth.views.password_reset_confirm uidb36=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.username }}

{% trans "Thanks for using our site!" %}
JAJAJAJA
{% blocktrans %}The {{ site_name }} team{% endblocktrans %}
	
{% endautoescape %}

link_manager/accounts/templates/signup_complete.html
{% extends "base.html" %}

{% block content %}

Signup complete.

{% endblock %}

link_manager/accounts/templates/user_change.html
{% extends "base_accounts_form.html" %}

{% block title %}Change your information
{% endblock %}

link_manager/accounts/templates/user_change_complete.html
{% extends "base.html" %}

{% block content %}

User Change complete.

{% endblock %}